[features]
seeds = false
skip-lint = false
[programs.localnet]
alpha_vault = "4bkUMyC4LTWzpEre3V5zJrnDAKQzmSf1qM7RWSri3env"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
