[features]
seeds = false
skip-lint = false

[programs.localnet]
alpha_vault = "4bkUMyC4LTWzpEre3V5zJrnDAKQzmSf1qM7RWSri3env"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keys/localnet/admin-bossj3JvwiNK7pvjr149DqdtJxf2gdygbcmEPTkb2F1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.28.0"